name:  Publish to crates.io
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-rust
        with:
          os: ubuntu-latest
          toolchain: stable
      - name: Run tests
        run: cargo test --locked --all-features
      - name: Build documentation
        run: cargo doc --no-deps --locked --all-features
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
